namespace SharePicker.Models.Fmp;

public class FullFinancialStatementDto
{
    public required string Date { get; init; }
    public required string Symbol { get; init; }
    public required decimal RevenueFromContractWithCustomerExcludingAssessedTax { get; init; }
    public required decimal CostOfGoodsAndServicesSold { get; init; }
    public required decimal GrossProfit { get; init; }
    public required decimal ResearchAndDevelopmentExpense { get; init; }
    public required decimal SellingGeneralAndAdministrativeExpense { get; init; }
    public required decimal OperatingExpenses { get; init; }
    public required decimal OperatingIncomeLoss { get; init; }
    public required decimal NonOperatingIncomeExpense { get; init; }
    public required decimal IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNonControllingInterest { get; init; }
    public required decimal IncomeTaxExpenseBenefit { get; init; }
    public required decimal NetIncomeLoss { get; init; }
    public required decimal EarningsPerShareBasic { get; init; }
    public required decimal EarningsPerShareDiluted { get; init; }
    public required decimal WeightedAverageNumberOfSharesOutstandingBasic { get; init; }
    public required decimal WeightedAverageNumberOfDilutedSharesOutstanding { get; init; }
    public required decimal OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax { get; init; }
    public required decimal OtherComprehensiveIncomeLossDerivativeInstrumentGainLossBeforereClassificationAfterTax { get; init; }
    public required decimal OtherComprehensiveIncomeLossDerivativeInstrumentGainLossReclassificationAfterTax { get; init; }
    public required decimal othercomprehensiveincomelossderivativeinstrumentgainlossafterreclassificationandtax { get; init; }
    public required decimal othercomprehensiveincomeunrealizedholdinggainlossonsecuritiesarisingduringperiodnetoftax { get; init; }
    public required decimal othercomprehensiveincomelossreclassificationadjustmentfromaociforsaleofsecuritiesnetoftax { get; init; }
    public required decimal othercomprehensiveincomelossavailableforsalesecuritiesadjustmentnetoftax { get; init; }
    public required decimal othercomprehensiveincomelossnetoftaxportionattributabletoparent { get; init; }
    public required decimal comprehensiveincomenetoftax { get; init; }
    public required decimal cashandcashequivalentsatcarryingvalue { get; init; }
    public required decimal marketablesecuritiescurrent { get; init; }
    public required decimal accountsreceivablenetcurrent { get; init; }
    public required decimal inventorynet { get; init; }
    public required decimal nontradereceivablescurrent { get; init; }
    public required decimal otherassetscurrent { get; init; }
    public required decimal assetscurrent { get; init; }
    public required decimal marketablesecuritiesnoncurrent { get; init; }
    public required decimal propertyplantandequipmentnet { get; init; }
    public required decimal otherassetsnoncurrent { get; init; }
    public required decimal assetsnoncurrent { get; init; }
    public required decimal assets { get; init; }
    public required decimal accountspayablecurrent { get; init; }
    public required decimal otherliabilitiescurrent { get; init; }
    public required decimal contractwithcustomerliabilitycurrent { get; init; }
    public required decimal commercialpaper { get; init; }
    public required decimal longtermdebtcurrent { get; init; }
    public required decimal liabilitiescurrent { get; init; }
    public required decimal longtermdebtnoncurrent { get; init; }
    public required decimal otherliabilitiesnoncurrent { get; init; }
    public required decimal liabilitiesnoncurrent { get; init; }
    public required decimal liabilities { get; init; }
    public required decimal commonstocksincludingadditionalpaidincapital { get; init; }
    public required decimal retainedearningsaccumulateddeficit { get; init; }
    public required decimal accumulatedothercomprehensiveincomelossnetoftax { get; init; }
    public required decimal stockholdersequity { get; init; }
    public required decimal liabilitiesandstockholdersequity { get; init; }
    public required decimal commonstockparorstatedvaluepershare { get; init; }
    public required decimal commonstocksharesauthorized { get; init; }
    public required decimal commonstocksharesissued { get; init; }
    public required decimal commonstocksharesoutstanding { get; init; }
    public required decimal stockissuedduringperiodvaluenewissues { get; init; }
    public required decimal adjustmentsrelatedtotaxwithholdingforsharebasedcompensation { get; init; }
    public required decimal adjustmentstoadditionalpaidincapitalsharebasedcompensationrequisiteserviceperiodrecognitionvalue { get; init; }
    public required decimal dividends { get; init; }
    public required decimal stockrepurchasedandretiredduringperiodvalue { get; init; }
    public required decimal commonstockdividendspersharedeclared { get; init; }
    public required decimal cashcashequivalentsrestrictedcashandrestrictedcashequivalents { get; init; }
    public required decimal depreciationdepletionandamortization { get; init; }
    public required decimal sharebasedcompensation { get; init; }
    public required decimal deferredincometaxexpensebenefit { get; init; }
    public required decimal othernoncashincomeexpense { get; init; }
    public required decimal increasedecreaseinaccountsreceivable { get; init; }
    public required decimal increasedecreaseininventories { get; init; }
    public required decimal increasedecreaseinotherreceivables { get; init; }
    public required decimal increasedecreaseinotheroperatingassets { get; init; }
    public required decimal increasedecreaseinaccountspayable { get; init; }
    public required decimal increasedecreaseincontractwithcustomerliability { get; init; }
    public required decimal increasedecreaseinotheroperatingliabilities { get; init; }
    public required decimal netcashprovidedbyusedinoperatingactivities { get; init; }
    public required decimal paymentstoacquireavailableforsalesecuritiesdebt { get; init; }
    public required decimal proceedsfrommaturitiesprepaymentsandcallsofavailableforsalesecurities { get; init; }
    public required decimal proceedsfromsaleofavailableforsalesecuritiesdebt { get; init; }
    public required decimal paymentstoacquirepropertyplantandequipment { get; init; }
    public required decimal paymentstoacquirebusinessesnetofcashacquired { get; init; }
    public required decimal paymentsforproceedsfromotherinvestingactivities { get; init; }
    public required decimal netcashprovidedbyusedininvestingactivities { get; init; }
    public required decimal paymentsrelatedtotaxwithholdingforsharebasedcompensation { get; init; }
    public required decimal paymentsofdividends { get; init; }
    public required decimal paymentsforrepurchaseofcommonstock { get; init; }
    public required decimal proceedsfromissuanceoflongtermdebt { get; init; }
    public required decimal repaymentsoflongtermdebt { get; init; }
    public required decimal proceedsfromrepaymentsofcommercialpaper { get; init; }
    public required decimal proceedsfrompaymentsforotherfinancingactivities { get; init; }
    public required decimal netcashprovidedbyusedinfinancingactivities { get; init; }
    public required decimal cashcashequivalentsrestrictedcashandrestrictedcashequivalentsperiodincreasedecreaseincludingexchangerateeffect { get; init; }
    public required decimal incometaxespaidnet { get; init; }
    public required decimal interestpaidnet { get; init; }
    public required decimal performanceobligationsinarrangements { get; init; }
    public required decimal propertyplantandequipmentusefullife { get; init; }
    public required decimal depreciation { get; init; }
    public required decimal weightedaveragenumberdilutedsharesoutstandingadjustment { get; init; }
    public required decimal contractwithcustomerliabilityrevenuerecognized { get; init; }
    public required decimal contractwithcustomerliability { get; init; }
    public required decimal revenueremainingperformanceobligationpercentage { get; init; }
    public required decimal revenueremainingperformanceobligationexpectedtimingofsatisfactionperiod1 { get; init; }
    public required decimal cash { get; init; }
    public required decimal equitysecuritiesfvnicost { get; init; }
    public required decimal equitysecuritiesfvniaccumulatedgrossunrealizedlossbeforetax { get; init; }
    public required decimal equitysecuritiesfvnicurrentandnoncurrent { get; init; }
    public required decimal availableforsaledebtsecuritiesamortizedcostbasis { get; init; }
    public required decimal availableforsaledebtsecuritiesaccumulatedgrossunrealizedgainbeforetax { get; init; }
    public required decimal availableforsaledebtsecuritiesaccumulatedgrossunrealizedlossbeforetax { get; init; }
    public required decimal availableforsalesecuritiesdebtsecurities { get; init; }
    public required decimal cashcashequivalentsandmarketablesecuritiescost { get; init; }
    public required decimal cashequivalentsandmarketablesecuritiesaccumulatedgrossunrealizedgainbeforetax { get; init; }
    public required decimal cashequivalentsandmarketablesecuritiesaccumulatedgrossunrealizedlossbeforetax { get; init; }
    public required decimal cashcashequivalentsandmarketablesecurities { get; init; }
    public required decimal restrictedinvestments { get; init; }
    public required decimal availableforsalesecuritiesdebtmaturitiesrollingyeartwothroughfivefairvalue { get; init; }
    public required decimal availableforsalesecuritiesdebtmaturitiesrollingyearsixthroughtenfairvalue { get; init; }
    public required decimal availableforsalesecuritiesdebtmaturitiesrollingafteryeartenfairvalue { get; init; }
    public required decimal availableforsalesecuritiesdebtmaturitiessinglematuritydate { get; init; }
    public required decimal maximumlengthoftimeforeigncurrencycashflowhedge { get; init; }
    public required decimal fairvalueconcentrationofriskderivativefinancialinstrumentsassets { get; init; }
    public required decimal derivativeassetsreductionformasternettingarrangementsincludingtheeffectsofcollateral { get; init; }
    public required decimal derivativeliabilitiesreductionformasternettingarrangementsincludingtheeffectsofcollateral { get; init; }
    public required decimal derivativefairvalueofderivativenet { get; init; }
    public required decimal numberofcustomerswithsignificantaccountsreceivablebalance { get; init; }
    public required decimal concentrationriskpercentage1 { get; init; }
    public required decimal numberofsignificantvendors { get; init; }
    public required decimal derivativenotionalamount { get; init; }
    public required decimal derivativeassetfairvaluegrossassetincludingnotsubjecttomasternettingarrangement { get; init; }
    public required decimal derivativeliabilityfairvaluegrossliabilityincludingnotsubjecttomasternettingarrangement { get; init; }
    public required decimal hedgedassetfairvaluehedge { get; init; }
    public required decimal hedgedliabilityfairvaluehedge { get; init; }
    public required decimal propertyplantandequipmentgross { get; init; }
    public required decimal accumulateddepreciationdepletionandamortizationpropertyplantandequipment { get; init; }
    public required decimal accruedincometaxesnoncurrent { get; init; }
    public required decimal otheraccruedliabilitiesnoncurrent { get; init; }
    public required decimal investmentincomeinterestanddividend { get; init; }
    public required decimal interestexpense { get; init; }
    public required decimal othernonoperatingincomeexpense { get; init; }
    public required decimal currentfederaltaxexpensebenefit { get; init; }
    public required decimal deferredfederalincometaxexpensebenefit { get; init; }
    public required decimal federalincometaxexpensebenefitcontinuingoperations { get; init; }
    public required decimal currentstateandlocaltaxexpensebenefit { get; init; }
    public required decimal deferredstateandlocalincometaxexpensebenefit { get; init; }
    public required decimal stateandlocalincometaxexpensebenefitcontinuingoperations { get; init; }
    public required decimal currentforeigntaxexpensebenefit { get; init; }
    public required decimal deferredforeignincometaxexpensebenefit { get; init; }
    public required decimal foreignincometaxexpensebenefitcontinuingoperations { get; init; }
    public required decimal incomelossfromcontinuingoperationsbeforeincometaxesforeign { get; init; }
    public required decimal effectiveincometaxratereconciliationatfederalstatutoryincometaxrate { get; init; }
    public required decimal deferredtaxassetstaxcreditcarryforwardsforeign { get; init; }
    public required decimal deferredtaxassetstaxcreditcarryforwardsresearch { get; init; }
    public required decimal unrecognizedtaxbenefits { get; init; }
    public required decimal unrecognizedtaxbenefitsthatwouldimpacteffectivetaxrate { get; init; }
    public required decimal decreaseinunrecognizedtaxbenefitsisreasonablypossible { get; init; }
    public required decimal losscontingencyestimateofpossibleloss { get; init; }
    public required decimal incometaxreconciliationincometaxexpensebenefitatfederalstatutoryincometaxrate { get; init; }
    public required decimal incometaxreconciliationstateandlocalincometaxes { get; init; }
    public required decimal effectiveincometaxratereconciliationtaxcutsandjobsactof2017amount { get; init; }
    public required decimal incometaxreconciliationforeignincometaxratedifferential { get; init; }
    public required decimal effectiveincometaxratereconciliationfdiiamount { get; init; }
    public required decimal incometaxreconciliationtaxcreditsresearch { get; init; }
    public required decimal effectiveincometaxratereconciliationsharebasedcompensationexcesstaxbenefitamount { get; init; }
    public required decimal incometaxreconciliationotheradjustments { get; init; }
    public required decimal effectiveincometaxratecontinuingoperations { get; init; }
    public required decimal deferredtaxassetsgoodwillandintangibleassets { get; init; }
    public required decimal deferredtaxassetstaxdeferredexpensereservesandaccruals { get; init; }
    public required decimal deferredtaxassetsleaseliabilities { get; init; }
    public required decimal deferredtaxassetsdeferredincome { get; init; }
    public required decimal deferredtaxassetsothercomprehensiveloss { get; init; }
    public required decimal deferredtaxassetstaxcreditcarryforwards { get; init; }
    public required decimal deferredtaxassetsother { get; init; }
    public required decimal deferredtaxassetsgross { get; init; }
    public required decimal deferredtaxassetsvaluationallowance { get; init; }
    public required decimal deferredtaxassetsnet { get; init; }
    public required decimal deferredtaxliabilitiesminimumtaxonforeignearnings { get; init; }
    public required decimal deferredtaxliabilitiesleasingarrangements { get; init; }
    public required decimal deferredtaxliabilitiesothercomprehensiveincome { get; init; }
    public required decimal deferredtaxliabilitiesother { get; init; }
    public required decimal deferredincometaxliabilities { get; init; }
    public required decimal deferredtaxassetsliabilitiesnet { get; init; }
    public required decimal unrecognizedtaxbenefitsincreasesresultingfrompriorperiodtaxpositions { get; init; }
    public required decimal unrecognizedtaxbenefitsdecreasesresultingfrompriorperiodtaxpositions { get; init; }
    public required decimal unrecognizedtaxbenefitsincreasesresultingfromcurrentperiodtaxpositions { get; init; }
    public required decimal unrecognizedtaxbenefitsdecreasesresultingfromsettlementswithtaxingauthorities { get; init; }
    public required decimal unrecognizedtaxbenefitsreductionsresultingfromlapseofapplicablestatuteoflimitations { get; init; }
    public required decimal lesseeoperatingandfinanceleasetermofcontract { get; init; }
    public required decimal operatingleasecost { get; init; }
    public required decimal variableleasecost { get; init; }
    public required decimal operatingleasepayments { get; init; }
    public required decimal rightofuseassetsobtainedinexchangeforoperatingandfinanceleaseliabilities { get; init; }
    public required decimal operatingandfinanceleaseweightedaverageremainingleaseterm { get; init; }
    public required decimal operatingandfinanceleaseweightedaveragediscountratepercent { get; init; }
    public required decimal lesseeoperatingandfinanceleaseleasenotyetcommencedpaymentsdue { get; init; }
    public required decimal lesseeoperatingandfinanceleaseleasenotyetcommencedtermofcontract { get; init; }
    public required decimal operatingleaserightofuseasset { get; init; }
    public required decimal operatingleaserightofuseassetstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal financeleaserightofuseasset { get; init; }
    public required decimal financeleaserightofuseassetstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal operatingandfinanceleaserightofuseasset { get; init; }
    public required decimal operatingleaseliabilitycurrent { get; init; }
    public required decimal operatingleaseliabilitycurrentstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal operatingleaseliabilitynoncurrent { get; init; }
    public required decimal operatingleaseliabilitynoncurrentstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal financeleaseliabilitycurrent { get; init; }
    public required decimal financeleaseliabilitycurrentstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal financeleaseliabilitynoncurrent { get; init; }
    public required decimal financeleaseliabilitynoncurrentstatementoffinancialpositionextensiblelist { get; init; }
    public required decimal operatingandfinanceleaseliability { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsduenexttwelvemonths { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdueyeartwo { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdueyearthree { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdueyearfour { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdueyearfive { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdueafteryearfive { get; init; }
    public required decimal lesseeoperatingleaseliabilitypaymentsdue { get; init; }
    public required decimal lesseeoperatingleaseliabilityundiscountedexcessamount { get; init; }
    public required decimal operatingleaseliability { get; init; }
    public required decimal financeleaseliabilitypaymentsduenexttwelvemonths { get; init; }
    public required decimal financeleaseliabilitypaymentsdueyeartwo { get; init; }
    public required decimal financeleaseliabilitypaymentsdueyearthree { get; init; }
    public required decimal financeleaseliabilitypaymentsdueyearfour { get; init; }
    public required decimal financeleaseliabilitypaymentsdueyearfive { get; init; }
    public required decimal financeleaseliabilitypaymentsdueafteryearfive { get; init; }
    public required decimal financeleaseliabilitypaymentsdue { get; init; }
    public required decimal financeleaseliabilityundiscountedexcessamount { get; init; }
    public required decimal financeleaseliability { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidyearone { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidyeartwo { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidyearthree { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidyearfour { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidyearfive { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitytobepaidafteryearfive { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilitypaymentsdue { get; init; }
    public required decimal lesseeoperatingandfinanceleaseliabilityundiscountedexcessamount { get; init; }
    public required decimal debtinstrumentterm { get; init; }
    public required decimal shorttermdebtweightedaverageinterestrate { get; init; }
    public required decimal interestcostsincurred { get; init; }
    public required decimal longtermdebtfairvalue { get; init; }
    public required decimal proceedsfromrepaymentsofshorttermdebtmaturinginthreemonthsorless { get; init; }
    public required decimal proceedsfromshorttermdebtmaturinginmorethanthreemonths { get; init; }
    public required decimal repaymentsofshorttermdebtmaturinginmorethanthreemonths { get; init; }
    public required decimal proceedsfromrepaymentsofshorttermdebtmaturinginmorethanthreemonths { get; init; }
    public required decimal debtinstrumentcarryingamount { get; init; }
    public required decimal debtinstrumentunamortizeddiscountpremiumanddebtissuancecostsnet { get; init; }
    public required decimal hedgeaccountingadjustmentsrelatedtolongtermdebt { get; init; }
    public required decimal debtinstrumentmaturityyearrangestart { get; init; }
    public required decimal debtinstrumentmaturityyearrangeend { get; init; }
    public required decimal debtinstrumentinterestratestatedpercentage { get; init; }
    public required decimal debtinstrumentinterestrateeffectivepercentage { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalinnexttwelvemonths { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalinyeartwo { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalinyearthree { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalinyearfour { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalinyearfive { get; init; }
    public required decimal longtermdebtmaturitiesrepaymentsofprincipalafteryearfive { get; init; }
    public required decimal stockrepurchasedandretiredduringperiodshares { get; init; }
    public required decimal stockissuedduringperiodsharessharebasedpaymentarrangementnetofshareswithheldfortaxes { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardawardvestingperiod1 { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsnumberofsharesofcommonstockissuedperunituponvesting { get; init; }
    public required decimal factorbywhicheachrsugrantedreducesandeachrsucanceledorsharewithheldfortaxesincreasessharesavailableforgrant { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardpurchasepriceofcommonstockpercent { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardofferingperiod { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardmaximumemployeesubscriptionrate { get; init; }
    public required decimal employeestockpurchaseplanmaximumannualpurchasesperemployeeamount { get; init; }
    public required decimal definedcontributionplanemployermatchingcontributionpercentofmatch { get; init; }
    public required decimal definedcontributionplanemployermatchingcontributionpercent { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsvestedinperiodtotalfairvalue { get; init; }
    public required decimal sharespaidfortaxwithholdingforsharebasedcompensation { get; init; }
    public required decimal employeeservicesharebasedcompensationnonvestedawardstotalcompensationcostnotyetrecognized { get; init; }
    public required decimal employeeservicesharebasedcompensationnonvestedawardstotalcompensationcostnotyetrecognizedperiodforrecognition1 { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsnonvestednumber { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsgrantsinperiod { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsvestedinperiod { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsforfeitedinperiod { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsnonvestedweightedaveragegrantdatefairvalue { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsgrantsinperiodweightedaveragegrantdatefairvalue { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsvestedinperiodweightedaveragegrantdatefairvalue { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsforfeituresweightedaveragegrantdatefairvalue { get; init; }
    public required decimal sharebasedcompensationarrangementbysharebasedpaymentawardequityinstrumentsotherthanoptionsaggregateintrinsicvaluenonvested { get; init; }
    public required decimal allocatedsharebasedcompensationexpense { get; init; }
    public required decimal employeeservicesharebasedcompensationtaxbenefitfromcompensationexpense { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationbalanceonfirstanniversary { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationbalanceonsecondanniversary { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationbalanceonthirdanniversary { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationbalanceonfourthanniversary { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationbalanceonfifthanniversary { get; init; }
    public required decimal unrecordedunconditionalpurchaseobligationdueafterfiveyears { get; init; }
    public required decimal UnrecordedUnconditionalPurchaseObligationBalanceSheetAmount { get; init; }
    public required decimal OtherGeneralAndAdministrativeExpense { get; init; }
    public required decimal NonCurrentAssets { get; init; }
}
